### PR TITLE
Gimbal debug

### PR DESCRIPTION
**Pull request by david-shearon**
To use a drone with a gimbal, use: make px4_sitl gazebo_typhoon_h480

### CODE REVIEW

**Comment by david-shearon** [comment]
In the end, all I did was change the line `self._submit_simple_generator(self._system.gimbal.control)` to `self._submit_generator(self._system.gimbal.control)`, which handles the StatusCode.UNAVAILABLE errors.

**Comment by carlsondev** [comment]
Do you have any verification on the server side that the gimbal calls had the desired effect (even though there were the _MultiThreadedRendevous errors) or are you just going off of the `pteranodon` logs saying it succeeded? Because if it didn't actually achieve the result then we are just silencing the errors. 

Do the

**Comment by david-shearon** [comment]
@carlsondev No, I loaded a gazebo drone with a gimbal and camera and basically ran through the gimbal.py test from MAVSDK. I could see it manipulating the gimbal. Very cool.

**Comment by david-shearon** [comment]
The tests I got were from MAVSDK, but I ran them through pteranodon

**Comment by carlsondev** [comment]
Okay I just wanted to make sure

**Review by justincdavis — APPROVED** [review]

**Pull request merged**
